baseurl = "/"
title = "William Pansky | Dallas, TX"
languageCode = "en-us"
theme = "pFlipboard"
metadataformat = "toml"
canonifyurls = true
menus = "main"
publishDir = "docs"
googleAnalytics = "UA-25458964-1"

[params]
  author = "William Pansky"
  URL = "http://williampansky.com"
  description = "Dallas, TX; Graphic designer & aspiring front-end webdev."
  subject = "Me, myself, and I."
  copyright = "© 2017 William Pansky."
  license = "Released under the MIT license."

[[menu.main]]
	name   = "Portfolio"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "LinkedIn*"
	url    = "https://www.linkedin.com/in/williampansky"
	weight = 20

[[menu.main]]
	name   = "Contact"
	url    = "/contact/"
	weight = 30

[blackfriday]
  smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
